import QtQuick

ListModel {
    ListElement { countryName: qsTr("安道尔"); countryCode: "AD" }
    ListElement { countryName: qsTr("阿拉伯联合酋长国"); countryCode: "AE" }
    ListElement { countryName: qsTr("阿富汗"); countryCode: "AF" }
    ListElement { countryName: qsTr("安提瓜和巴布达"); countryCode: "AG" }
    ListElement { countryName: qsTr("安圭拉"); countryCode: "AI" }
    ListElement { countryName: qsTr("阿尔巴尼亚"); countryCode: "AL" }
    ListElement { countryName: qsTr("亚美尼亚"); countryCode: "AM" }
    ListElement { countryName: qsTr("安哥拉"); countryCode: "AO" }
    ListElement { countryName: qsTr("阿根廷"); countryCode: "AR" }
    ListElement { countryName: qsTr("美属萨摩亚"); countryCode: "AS" }
    ListElement { countryName: qsTr("奥地利"); countryCode: "AT" }
    ListElement { countryName: qsTr("阿鲁巴"); countryCode: "AW" }
    ListElement { countryName: qsTr("阿塞拜疆"); countryCode: "AZ" }
    ListElement { countryName: qsTr("波斯尼亚和黑塞哥维那"); countryCode: "BA" }
    ListElement { countryName: qsTr("巴巴多斯"); countryCode: "BB" }
    ListElement { countryName: qsTr("孟加拉国"); countryCode: "BD" }
    ListElement { countryName: qsTr("比利时"); countryCode: "BE" }
    ListElement { countryName: qsTr("布基纳法索"); countryCode: "BF" }
    ListElement { countryName: qsTr("保加利亚"); countryCode: "BG" }
    ListElement { countryName: qsTr("巴林"); countryCode: "BH" }
    ListElement { countryName: qsTr("布隆迪"); countryCode: "BI" }
    ListElement { countryName: qsTr("贝宁"); countryCode: "BJ" }
    ListElement { countryName: qsTr("百慕大"); countryCode: "BM" }
    ListElement { countryName: qsTr("文莱"); countryCode: "BN" }
    ListElement { countryName: qsTr("玻利维亚"); countryCode: "BO" }
    ListElement { countryName: qsTr("巴西"); countryCode: "BR" }
    ListElement { countryName: qsTr("巴哈马"); countryCode: "BS" }
    ListElement { countryName: qsTr("不丹"); countryCode: "BT" }
    ListElement { countryName: qsTr("博茨瓦纳"); countryCode: "BW" }
    ListElement { countryName: qsTr("白俄罗斯"); countryCode: "BY" }
    ListElement { countryName: qsTr("伯利兹"); countryCode: "BZ" }
    ListElement { countryName: qsTr("加拿大"); countryCode: "CA" }
    ListElement { countryName: qsTr("中非共和国"); countryCode: "CF" }
    ListElement { countryName: qsTr("刚果共和国"); countryCode: "CG" }
    ListElement { countryName: qsTr("瑞士"); countryCode: "CH" }
    ListElement { countryName: qsTr("科特迪瓦"); countryCode: "CI" }
    ListElement { countryName: qsTr("库克群岛"); countryCode: "CK" }
    ListElement { countryName: qsTr("智利"); countryCode: "CL" }
    ListElement { countryName: qsTr("喀麦隆"); countryCode: "CM" }
    ListElement { countryName: qsTr("中国"); countryCode: "CN" }
    ListElement { countryName: qsTr("哥伦比亚"); countryCode: "CO" }
    ListElement { countryName: qsTr("哥斯达黎加"); countryCode: "CR" }
    ListElement { countryName: qsTr("古巴"); countryCode: "CU" }
    ListElement { countryName: qsTr("佛得角"); countryCode: "CV" }
    ListElement { countryName: qsTr("塞浦路斯"); countryCode: "CY" }
    ListElement { countryName: qsTr("捷克"); countryCode: "CZ" }
    ListElement { countryName: qsTr("德国"); countryCode: "DE" }
    ListElement { countryName: qsTr("吉布提"); countryCode: "DJ" }
    ListElement { countryName: qsTr("丹麦"); countryCode: "DK" }
    ListElement { countryName: qsTr("多米尼克"); countryCode: "DM" }
    ListElement { countryName: qsTr("多米尼加共和国"); countryCode: "DO" }
    ListElement { countryName: qsTr("阿尔及利亚"); countryCode: "DZ" }
    ListElement { countryName: qsTr("厄瓜多尔"); countryCode: "EC" }
    ListElement { countryName: qsTr("爱沙尼亚"); countryCode: "EE" }
    ListElement { countryName: qsTr("埃及"); countryCode: "EG" }
    ListElement { countryName: qsTr("厄立特里亚"); countryCode: "ER" }
    ListElement { countryName: qsTr("西班牙"); countryCode: "ES" }
    ListElement { countryName: qsTr("埃塞俄比亚"); countryCode: "ET" }
    ListElement { countryName: qsTr("芬兰"); countryCode: "FI" }
    ListElement { countryName: qsTr("斐济"); countryCode: "FJ" }
    ListElement { countryName: qsTr("福克兰群岛"); countryCode: "FK" }
    ListElement { countryName: qsTr("法罗群岛"); countryCode: "FO" }
    ListElement { countryName: qsTr("法国"); countryCode: "FR" }
    ListElement { countryName: qsTr("加蓬"); countryCode: "GA" }
    ListElement { countryName: qsTr("英国"); countryCode: "GB" }
    ListElement { countryName: qsTr("格林纳达"); countryCode: "GD" }
    ListElement { countryName: qsTr("格鲁吉亚"); countryCode: "GE" }
    ListElement { countryName: qsTr("法属圭亚那"); countryCode: "GF" }
    ListElement { countryName: qsTr("加纳"); countryCode: "GH" }
    ListElement { countryName: qsTr("直布罗陀"); countryCode: "GI" }
    ListElement { countryName: qsTr("格陵兰"); countryCode: "GL" }
    ListElement { countryName: qsTr("冈比亚"); countryCode: "GM" }
    ListElement { countryName: qsTr("几内亚"); countryCode: "GN" }
    ListElement { countryName: qsTr("赤道几内亚"); countryCode: "GQ" }
    ListElement { countryName: qsTr("希腊"); countryCode: "GR" }
    ListElement { countryName: qsTr("危地马拉"); countryCode: "GT" }
    ListElement { countryName: qsTr("关岛"); countryCode: "GU" }
    ListElement { countryName: qsTr("几内亚比绍"); countryCode: "GW" }
    ListElement { countryName: qsTr("圭亚那"); countryCode: "GY" }
    ListElement { countryName: qsTr("香港"); countryCode: "HK" }
    ListElement { countryName: qsTr("洪都拉斯"); countryCode: "HN" }
    ListElement { countryName: qsTr("克罗地亚"); countryCode: "HR" }
    ListElement { countryName: qsTr("海地"); countryCode: "HT" }
    ListElement { countryName: qsTr("匈牙利"); countryCode: "HU" }
    ListElement { countryName: qsTr("印度尼西亚"); countryCode: "ID" }
    ListElement { countryName: qsTr("爱尔兰"); countryCode: "IE" }
    ListElement { countryName: qsTr("以色列"); countryCode: "IL" }
    ListElement { countryName: qsTr("印度"); countryCode: "IN" }
    ListElement { countryName: qsTr("伊拉克"); countryCode: "IQ" }
    ListElement { countryName: qsTr("伊朗"); countryCode: "IR" }
    ListElement { countryName: qsTr("冰岛"); countryCode: "IS" }
    ListElement { countryName: qsTr("意大利"); countryCode: "IT" }
    ListElement { countryName: qsTr("牙买加"); countryCode: "JM" }
    ListElement { countryName: qsTr("约旦"); countryCode: "JO" }
    ListElement { countryName: qsTr("日本"); countryCode: "JP" }
    ListElement { countryName: qsTr("肯尼亚"); countryCode: "KE" }
    ListElement { countryName: qsTr("吉尔吉斯斯坦"); countryCode: "KG" }
    ListElement { countryName: qsTr("柬埔寨"); countryCode: "KH" }
    ListElement { countryName: qsTr("基里巴斯"); countryCode: "KI" }
    ListElement { countryName: qsTr("科摩罗"); countryCode: "KM" }
    ListElement { countryName: qsTr("朝鲜"); countryCode: "KP" }
    ListElement { countryName: qsTr("韩国"); countryCode: "KR" }
    ListElement { countryName: qsTr("科威特"); countryCode: "KW" }
    ListElement { countryName: qsTr("开曼群岛"); countryCode: "KY" }
    ListElement { countryName: qsTr("哈萨克斯坦"); countryCode: "KZ" }
    ListElement { countryName: qsTr("老挝"); countryCode: "LA" }
    ListElement { countryName: qsTr("黎巴嫩"); countryCode: "LB" }
    ListElement { countryName: qsTr("圣卢西亚"); countryCode: "LC" }
    ListElement { countryName: qsTr("列支敦士登"); countryCode: "LI" }
    ListElement { countryName: qsTr("斯里兰卡"); countryCode: "LK" }
    ListElement { countryName: qsTr("利比里亚"); countryCode: "LR" }
    ListElement { countryName: qsTr("莱索托"); countryCode: "LS" }
    ListElement { countryName: qsTr("立陶宛"); countryCode: "LT" }
    ListElement { countryName: qsTr("卢森堡"); countryCode: "LU" }
    ListElement { countryName: qsTr("拉脱维亚"); countryCode: "LV" }
    ListElement { countryName: qsTr("利比亚"); countryCode: "LY" }
    ListElement { countryName: qsTr("摩洛哥"); countryCode: "MA" }
    ListElement { countryName: qsTr("摩纳哥"); countryCode: "MC" }
    ListElement { countryName: qsTr("摩尔多瓦"); countryCode: "MD" }
    ListElement { countryName: qsTr("黑山"); countryCode: "ME" }
    ListElement { countryName: qsTr("马达加斯加"); countryCode: "MG" }
    ListElement { countryName: qsTr("北马其顿"); countryCode: "MK" }
    ListElement { countryName: qsTr("马里"); countryCode: "ML" }
    ListElement { countryName: qsTr("缅甸"); countryCode: "MM" }
    ListElement { countryName: qsTr("蒙古"); countryCode: "MN" }
    ListElement { countryName: qsTr("澳门"); countryCode: "MO" }
    ListElement { countryName: qsTr("毛里塔尼亚"); countryCode: "MR" }
    ListElement { countryName: qsTr("蒙特塞拉特"); countryCode: "MS" }
    ListElement { countryName: qsTr("马耳他"); countryCode: "MT" }
    ListElement { countryName: qsTr("毛里求斯"); countryCode: "MU" }
    ListElement { countryName: qsTr("马尔代夫"); countryCode: "MV" }
    ListElement { countryName: qsTr("马拉维"); countryCode: "MW" }
    ListElement { countryName: qsTr("墨西哥"); countryCode: "MX" }
    ListElement { countryName: qsTr("马来西亚"); countryCode: "MY" }
    ListElement { countryName: qsTr("莫桑比克"); countryCode: "MZ" }
    ListElement { countryName: qsTr("纳米比亚"); countryCode: "NA" }
    ListElement { countryName: qsTr("新喀里多尼亚"); countryCode: "NC" }
    ListElement { countryName: qsTr("尼日尔"); countryCode: "NE" }
    ListElement { countryName: qsTr("诺福克岛"); countryCode: "NF" }
    ListElement { countryName: qsTr("尼日利亚"); countryCode: "NG" }
    ListElement { countryName: qsTr("尼加拉瓜"); countryCode: "NI" }
    ListElement { countryName: qsTr("荷兰"); countryCode: "NL" }
    ListElement { countryName: qsTr("挪威"); countryCode: "NO" }
    ListElement { countryName: qsTr("尼泊尔"); countryCode: "NP" }
    ListElement { countryName: qsTr("瑙鲁"); countryCode: "NR" }
    ListElement { countryName: qsTr("纽埃"); countryCode: "NU" }
    ListElement { countryName: qsTr("新西兰"); countryCode: "NZ" }
    ListElement { countryName: qsTr("阿曼"); countryCode: "OM" }
    ListElement { countryName: qsTr("巴拿马"); countryCode: "PA" }
    ListElement { countryName: qsTr("秘鲁"); countryCode: "PE" }
    ListElement { countryName: qsTr("法属波利尼西亚"); countryCode: "PF" }
    ListElement { countryName: qsTr("巴布亚新几内亚"); countryCode: "PG" }
    ListElement { countryName: qsTr("菲律宾"); countryCode: "PH" }
    ListElement { countryName: qsTr("巴基斯坦"); countryCode: "PK" }
    ListElement { countryName: qsTr("波兰"); countryCode: "PL" }
    ListElement { countryName: qsTr("圣皮埃尔和密克隆"); countryCode: "PM" }
    ListElement { countryName: qsTr("波多黎各"); countryCode: "PR" }
    ListElement { countryName: qsTr("葡萄牙"); countryCode: "PT" }
    ListElement { countryName: qsTr("帕劳"); countryCode: "PW" }
    ListElement { countryName: qsTr("巴拉圭"); countryCode: "PY" }
    ListElement { countryName: qsTr("卡塔尔"); countryCode: "QA" }
    ListElement { countryName: qsTr("罗马尼亚"); countryCode: "RO" }
    ListElement { countryName: qsTr("塞尔维亚"); countryCode: "RS" }
    ListElement { countryName: qsTr("俄罗斯"); countryCode: "RU" }
    ListElement { countryName: qsTr("卢旺达"); countryCode: "RW" }
    ListElement { countryName: qsTr("沙特阿拉伯"); countryCode: "SA" }
    ListElement { countryName: qsTr("所罗门群岛"); countryCode: "SB" }
    ListElement { countryName: qsTr("塞舌尔"); countryCode: "SC" }
    ListElement { countryName: qsTr("苏丹"); countryCode: "SD" }
    ListElement { countryName: qsTr("瑞典"); countryCode: "SE" }
    ListElement { countryName: qsTr("新加坡"); countryCode: "SG" }
    ListElement { countryName: qsTr("圣赫勒拿"); countryCode: "SH" }
    ListElement { countryName: qsTr("斯洛文尼亚"); countryCode: "SI" }
    ListElement { countryName: qsTr("斯洛伐克"); countryCode: "SK" }
    ListElement { countryName: qsTr("塞拉利昂"); countryCode: "SL" }
    ListElement { countryName: qsTr("圣马力诺"); countryCode: "SM" }
    ListElement { countryName: qsTr("塞内加尔"); countryCode: "SN" }
    ListElement { countryName: qsTr("索马里"); countryCode: "SO" }
    ListElement { countryName: qsTr("苏里南"); countryCode: "SR" }
    ListElement { countryName: qsTr("圣多美和普林西比"); countryCode: "ST" }
    ListElement { countryName: qsTr("萨尔瓦多"); countryCode: "SV" }
    ListElement { countryName: qsTr("叙利亚"); countryCode: "SY" }
    ListElement { countryName: qsTr("斯威士兰"); countryCode: "SZ" }
    ListElement { countryName: qsTr("特克斯和凯科斯群岛"); countryCode: "TC" }
    ListElement { countryName: qsTr("乍得"); countryCode: "TD" }
    ListElement { countryName: qsTr("多哥"); countryCode: "TG" }
    ListElement { countryName: qsTr("泰国"); countryCode: "TH" }
    ListElement { countryName: qsTr("塔吉克斯坦"); countryCode: "TJ" }
    ListElement { countryName: qsTr("东帝汶"); countryCode: "TL" }
    ListElement { countryName: qsTr("土库曼斯坦"); countryCode: "TM" }
    ListElement { countryName: qsTr("突尼斯"); countryCode: "TN" }
    ListElement { countryName: qsTr("汤加"); countryCode: "TO" }
    ListElement { countryName: qsTr("土耳其"); countryCode: "TR" }
    ListElement { countryName: qsTr("特立尼达和多巴哥"); countryCode: "TT" }
    ListElement { countryName: qsTr("台湾"); countryCode: "TW" }
    ListElement { countryName: qsTr("坦桑尼亚"); countryCode: "TZ" }
    ListElement { countryName: qsTr("乌克兰"); countryCode: "UA" }
    ListElement { countryName: qsTr("乌干达"); countryCode: "UG" }
    ListElement { countryName: qsTr("美国"); countryCode: "US" }
    ListElement { countryName: qsTr("乌拉圭"); countryCode: "UY" }
    ListElement { countryName: qsTr("乌兹别克斯坦"); countryCode: "UZ" }
    ListElement { countryName: qsTr("圣文森特和格林纳丁斯"); countryCode: "VC" }
    ListElement { countryName: qsTr("委内瑞拉"); countryCode: "VE" }
    ListElement { countryName: qsTr("英属维尔京群岛"); countryCode: "VG" }
    ListElement { countryName: qsTr("越南"); countryCode: "VN" }
    ListElement { countryName: qsTr("瓦努阿图"); countryCode: "VU" }
    ListElement { countryName: qsTr("萨摩亚"); countryCode: "WS" }
    ListElement { countryName: qsTr("也门"); countryCode: "YE" }
    ListElement { countryName: qsTr("南非"); countryCode: "ZA" }
    ListElement { countryName: qsTr("赞比亚"); countryCode: "ZM" }
    ListElement { countryName: qsTr("津巴布韦"); countryCode: "ZW" }
    ListElement { countryName: qsTr("刚果民主共和国"); countryCode: "CD" }
    ListElement { countryName: qsTr("澳大利亚"); countryCode: "AU" }
}
